Repository WhatSEOUL/WhatSeoul, pull requests merged in 2024-05, with the labels that each got.

#22 [FEAT] 서울 실시간 도시데이터 api - 인구 데이터에 인구 예측 지표도 함께 가져오기
  src/main/java/com/example/whatseoul/dto/CityData.java
  src/main/java/com/example/whatseoul/entity/CultureEvent.java
  src/main/java/com/example/whatseoul/entity/Population.java
  src/main/java/com/example/whatseoul/entity/PopulationForecast.java
  src/main/java/com/example/whatseoul/entity/Weather.java
  src/main/java/com/example/whatseoul/respository/cityData/PopulationForecastRepository.java
  src/main/java/com/example/whatseoul/service/ApiScheduler.java
Labels: ✨ FEAT

#24 [FEAT] 날씨 데이터 service, controller 구현
  src/main/java/com/example/whatseoul/WhatSeoulApplication.java
  src/main/java/com/example/whatseoul/controller/WeatherController.java
  src/main/java/com/example/whatseoul/dto/response/WeatherDataDto.java
  src/main/java/com/example/whatseoul/entity/Area.java
  src/main/java/com/example/whatseoul/respository/cityData/AreaRepository.java
  src/main/java/com/example/whatseoul/respository/cityData/WeatherRepository.java
  src/main/java/com/example/whatseoul/service/AlanService.java
  src/main/java/com/example/whatseoul/service/ApiScheduler.java
  src/main/java/com/example/whatseoul/service/WeatherService.java
Labels: ✨ FEAT

#28 [FEAT] 인구데이터 조회 api 구현 및 ui 1차 연동
  src/main/java/com/example/whatseoul/controller/PopulationController.java
  src/main/java/com/example/whatseoul/controller/citydata/CityDataController.java
  src/main/java/com/example/whatseoul/controller/citydata/CityDataViewController.java
  src/main/java/com/example/whatseoul/dto/response/PopulationDataDto.java
  src/main/java/com/example/whatseoul/dto/response/PopulationForecastDataDto.java
  src/main/java/com/example/whatseoul/entity/PopulationForecast.java
  src/main/java/com/example/whatseoul/respository/cityData/PopulationForecastRepository.java
  src/main/java/com/example/whatseoul/respository/cityData/PopulationRepository.java
  src/main/java/com/example/whatseoul/service/ApiScheduler.java
  src/main/java/com/example/whatseoul/service/PopulationService.java
  src/main/resources/static/css/citydata/citydatalist.css
  src/main/resources/static/js/citydata/population.js
  src/main/resources/static/js/selectarea/selectconfirm.js
  src/main/resources/templates/citydata/citydatalist.html
  src/main/resources/templates/index/index.html
  src/main/resources/templates/selectarea/selectconfirm.html
Labels: ✨ FEAT

#31 [FEAT] SSE로 앨런 AI 응답받은 값 반환
  build.gradle
  src/main/java/com/example/whatseoul/config/WebClientConfig.java
  src/main/java/com/example/whatseoul/controller/SseController.java
  src/main/java/com/example/whatseoul/dto/response/AlanResponseDto.java
  src/main/java/com/example/whatseoul/entity/Area.java
  src/main/java/com/example/whatseoul/service/AlanService.java
  src/main/java/com/example/whatseoul/service/ApiScheduler.java
  src/main/java/com/example/whatseoul/service/WeatherService.java
  src/main/java/com/example/whatseoul/service/WebClientService.java
Labels: ✨ FEAT

#34 [FEAT] 앨런 api 단순질의 답변 조회하도록 연동
  src/main/java/com/example/whatseoul/config/WebClientConfig.java
  src/main/java/com/example/whatseoul/controller/AlanController.java
  src/main/java/com/example/whatseoul/controller/AlanViewController.java
  src/main/java/com/example/whatseoul/controller/SseController.java
  src/main/java/com/example/whatseoul/dto/response/AlanBasicResponseDto.java
  src/main/java/com/example/whatseoul/dto/response/AlanResponseDto.java
  src/main/java/com/example/whatseoul/service/AlanService.java
  src/main/resources/static/js/alan/alan.js
  src/main/resources/templates/alan/alan.html
Labels: ✨ FEAT

#35 ✨ feat: 서울 실시간 도시데이터 - 문화 행사 API 뷰, 서비스, 컨트롤러 작성
  src/main/java/com/example/whatseoul/controller/CultureEventController.java
  src/main/java/com/example/whatseoul/dto/response/CultureEventDto.java
  src/main/java/com/example/whatseoul/respository/cityData/CulturalEventRepository.java
  src/main/java/com/example/whatseoul/service/CultureEventService.java
  src/main/resources/templates/events.html
Labels: ✨ FEAT

#36 [FEAT] 게시글 기능 구현
  build.gradle
  src/main/java/com/example/whatseoul/WhatSeoulApplication.java
  src/main/java/com/example/whatseoul/controller/PostController.java
  src/main/java/com/example/whatseoul/entity/Post.java
  src/main/java/com/example/whatseoul/repository/PostRepository.java
  src/main/java/com/example/whatseoul/service/PostService.java
  src/main/resources/templates/postedit.html
  src/main/resources/templates/postlist.html
  src/main/resources/templates/postview.html
  src/main/resources/templates/postwrite.html
Labels: ✨ FEAT

#38 [FEAT] 앨런 실시간 응답 기능 구현
  src/main/java/com/example/whatseoul/WhatSeoulApplication.java
  src/main/java/com/example/whatseoul/controller/AlanViewController.java
  src/main/java/com/example/whatseoul/controller/SseController.java
  src/main/java/com/example/whatseoul/service/AlanService.java
  src/main/java/com/example/whatseoul/service/ApiScheduler.java
  src/main/java/com/example/whatseoul/service/WebClientService.java
  src/main/resources/static/js/alan/alansse.js
  src/main/resources/templates/alan/alansse.html
Labels: ✨ FEAT

#43 ✨ feat : 실시간 도시데이터 UI 구현
  build.gradle
  src/main/java/com/example/whatseoul/controller/CultureEventController.java
  src/main/java/com/example/whatseoul/controller/WeatherController.java
  src/main/java/com/example/whatseoul/service/ApiScheduler.java
  src/main/java/com/example/whatseoul/service/CultureEventService.java
  src/main/resources/static/css/citydata/citydatalist.css
  src/main/resources/static/js/citydata/event.js
  src/main/resources/static/js/citydata/population.js
  src/main/resources/static/js/citydata/weather.js
  src/main/resources/templates/citydata/citydatalist.html
Labels: ✨ FEAT

#44 [FEAT] 앨런에게 명소 추천받기 UI 구현
  src/main/java/com/example/whatseoul/controller/alan/AlanController.java
  src/main/java/com/example/whatseoul/controller/alan/AlanViewController.java
  src/main/java/com/example/whatseoul/controller/alan/SseController.java
  src/main/resources/static/css/alan/alansse.css
  src/main/resources/static/js/alan/alansse.js
  src/main/resources/static/media/alan_logo_no_bg_square.png
  src/main/resources/static/media/ask_allan.png
  src/main/resources/static/media/loading.gif
  src/main/resources/static/media/user_profile.png
  src/main/resources/templates/alan/alansse.html
  src/main/resources/templates/citydata/citydatalist.html
  src/main/resources/templates/index/index.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/selectarea/selectareaname.html
  src/main/resources/templates/selectarea/selectconfirm.html
  src/main/resources/templates/selectarea/selectdistrict.html
Labels: ✨ FEAT

#51 Feat/#45
  src/main/java/com/example/whatseoul/config/SecurityConfig.java
  src/main/java/com/example/whatseoul/config/WebSecurityConfig.java
  src/main/java/com/example/whatseoul/controller/TestController.java
  src/main/java/com/example/whatseoul/controller/TestRepository.java
  src/main/java/com/example/whatseoul/controller/WebController.java
  src/main/java/com/example/whatseoul/controller/mypage/MyPageController.java
  src/main/java/com/example/whatseoul/controller/mypage/UpdateController.java
  src/main/java/com/example/whatseoul/entity/Test.java
  src/main/java/com/example/whatseoul/entity/User.java
  src/main/java/com/example/whatseoul/respository/TestRepositoryCustom.java
  src/main/java/com/example/whatseoul/respository/TestRepositoryImpl.java
  src/main/java/com/example/whatseoul/respository/user/UserRepository.java
  src/main/java/com/example/whatseoul/service/AccountService.java
  src/main/java/com/example/whatseoul/util/LoginUtil.java
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage/me.html
  src/main/resources/templates/register.html
  src/main/resources/templates/update.html
Labels: ✨ FEAT

#59 [FEAT] 유저 관련 기능 구현 추가
  src/main/java/com/example/whatseoul/controller/citydata/CityDataViewController.java
  src/main/java/com/example/whatseoul/repository/cityData/PopulationForecastRepository.java
  src/main/java/com/example/whatseoul/security/CustomUserDetails.java
Labels: ✨ FEAT

#70 [FEAT] 지역별 위치, 특색 정보 저장 기능 구현 및 지역 선택 ui 카카오맵 연동
  src/main/java/com/example/whatseoul/WhatSeoulApplication.java
  src/main/java/com/example/whatseoul/controller/alan/AlanController.java
  src/main/java/com/example/whatseoul/controller/citydata/AreaController.java
  src/main/java/com/example/whatseoul/dto/request/AreaRequestDto.java
  src/main/java/com/example/whatseoul/dto/response/AreaResponseDto.java
  src/main/java/com/example/whatseoul/entity/Area.java
  src/main/java/com/example/whatseoul/repository/cityData/AreaRepository.java
  src/main/java/com/example/whatseoul/service/AlanService.java
  src/main/java/com/example/whatseoul/service/AreaService.java
  src/main/resources/static/css/alan/alansse.css
  src/main/resources/static/css/selectarea/selectareaname.css
  src/main/resources/static/js/alan/alansse.js
  src/main/resources/static/js/selectarea/selectareaname.js
  src/main/resources/templates/alan/alansse.html
  src/main/resources/templates/selectarea/selectareaname.html
Labels: ✨ FEAT

#76 [FEAT]후기 게시판 네비게이션 바(HTML) 추가 및 댓글 프론트 수정
  src/main/java/com/example/whatseoul/controller/PostController.java
  src/main/java/com/example/whatseoul/service/PostService.java
  src/main/resources/static/css/index/index.css
  src/main/resources/static/css/post/post.css
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postDetail.html
  src/main/resources/templates/post/postView.html
  src/main/resources/templates/postedit.html
Labels: ✨ FEAT

#77 [REFACTOR] index.html에 존재하는 헤더를 공통으로 구현
  src/main/resources/static/css/header/header.css
  src/main/resources/static/css/index/index.css
  src/main/resources/static/css/post/postDetail.css
  src/main/resources/static/css/post/postView.css
  src/main/resources/static/css/user/login.css
  src/main/resources/templates/alan/alansse.html
  src/main/resources/templates/citydata/citydatalist.html
  src/main/resources/templates/header/header.html
  src/main/resources/templates/index/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postDetail.html
  src/main/resources/templates/post/postView.html
  src/main/resources/templates/postlist.html
  src/main/resources/templates/postview.html
  src/main/resources/templates/postwrite.html
  src/main/resources/templates/selectarea/selectareaname.html
  src/main/resources/templates/selectarea/selectconfirm.html
  src/main/resources/templates/selectarea/selectdistrict.html
  src/main/resources/templates/user/me.html
  src/main/resources/templates/user/register.html
  src/main/resources/templates/user/update.html
Labels: ♻️ REFACTOR

#78 [FEAT] 지역별 좌표를 저장하는 기능 구현(카카오 로컬 api 연동)
  src/main/java/com/example/whatseoul/controller/alan/AlanController.java
  src/main/java/com/example/whatseoul/controller/citydata/AreaController.java
  src/main/java/com/example/whatseoul/dto/response/KakaoResponseDto.java
  src/main/java/com/example/whatseoul/dto/response/LatLongResponseDto.java
  src/main/java/com/example/whatseoul/entity/Area.java
  src/main/java/com/example/whatseoul/repository/cityData/AreaRepository.java
  src/main/java/com/example/whatseoul/service/AlanService.java
  src/main/java/com/example/whatseoul/service/ApiScheduler.java
  src/main/java/com/example/whatseoul/service/AreaService.java
  src/main/resources/static/css/index/index.css
  src/main/resources/static/css/selectarea/selectareaname.css
  src/main/resources/static/js/selectarea/selectareaname.js
  src/main/resources/static/js/selectarea/selectdistrict.js
  src/main/resources/static/media/alan-question.PNG
  src/main/resources/static/media/citydata-view.png
  src/main/resources/templates/citydata/citydatalist.html
  src/main/resources/templates/index/index.html
Labels: ✨ FEAT

#83 🐛 fix: postEdit.css 생성 및 수정
  src/main/java/com/example/whatseoul/entity/Post.java
  src/main/resources/static/css/post/postEdit.css
  src/main/resources/templates/postedit.html
Labels: 🐛 FIX

#86 🐛 fix: 수정 후 버튼 실종 사건 해결
  src/main/java/com/example/whatseoul/controller/PostController.java
  src/main/java/com/example/whatseoul/service/PostService.java
Labels: 🐛 FIX

#87 [MERGE] develop 브랜치를 release 브랜치로 머지
  src/main/java/com/example/whatseoul/controller/PostController.java
  src/main/java/com/example/whatseoul/service/PostService.java
Labels: 🔥 MERGE

#88 [FIX] 문화행사 데이터 조회 ui 수정
  src/main/java/com/example/whatseoul/controller/citydata/CityDataViewController.java
  src/main/java/com/example/whatseoul/service/AreaService.java
  src/main/resources/static/css/citydata/citydatalist.css
  src/main/resources/static/js/citydata/event.js
  src/main/resources/templates/selectarea/selectareaname.html
Labels: 💄 STYLE

#89 [TEST] 도시데이터 조회 테스트 코드 작성
  src/test/java/com/example/whatseoul/service/ApiSchedulerTest.java
  src/test/java/com/example/whatseoul/service/CultureEventServiceTest.java
  src/test/java/com/example/whatseoul/service/PopulationServiceTest.java
  src/test/java/com/example/whatseoul/service/WeatherServiceTest.java
Labels: ✏️ test

#90 [MERGE] 브랜치를 머지합니다.
  README.md
  src/main/java/com/example/whatseoul/WhatSeoulApplication.java
  src/main/java/com/example/whatseoul/config/SecurityConfig.java
  src/main/java/com/example/whatseoul/controller/CommentController.java
  src/main/java/com/example/whatseoul/controller/CultureEventController.java
  src/main/java/com/example/whatseoul/controller/PopulationController.java
  src/main/java/com/example/whatseoul/controller/PostController.java
  src/main/java/com/example/whatseoul/controller/account/UserController.java
  src/main/java/com/example/whatseoul/controller/alan/AlanController.java
  src/main/java/com/example/whatseoul/controller/alan/SseController.java
  src/main/java/com/example/whatseoul/controller/citydata/AreaController.java
  src/main/java/com/example/whatseoul/controller/citydata/CityDataViewController.java
  src/main/java/com/example/whatseoul/dto/CommentDto.java
  src/main/java/com/example/whatseoul/dto/PostDto.java
  src/main/java/com/example/whatseoul/dto/ResponseDto.java
  src/main/java/com/example/whatseoul/dto/UserDto.java
  src/main/java/com/example/whatseoul/dto/request/AreaRequestDto.java
  src/main/java/com/example/whatseoul/dto/response/AlanBasicResponseDto.java
  src/main/java/com/example/whatseoul/dto/response/AlanResponseDto.java
  src/main/java/com/example/whatseoul/dto/response/PopulationDataDto.java
  src/main/java/com/example/whatseoul/entity/CultureEvent.java
  src/main/java/com/example/whatseoul/entity/Post.java
  src/main/java/com/example/whatseoul/exception/ResourceNotFoundException.java
  src/main/java/com/example/whatseoul/repository/cityData/AreaRepository.java
  src/main/java/com/example/whatseoul/security/CustomUserDetails.java
  src/main/java/com/example/whatseoul/security/LoginAuthenticationSuccessHandler.java
  src/main/java/com/example/whatseoul/service/AccountService.java
  src/main/java/com/example/whatseoul/service/AlanService.java
  src/main/java/com/example/whatseoul/service/ApiScheduler.java
  src/main/java/com/example/whatseoul/service/AreaService.java
  src/main/java/com/example/whatseoul/service/CommentService.java
  src/main/java/com/example/whatseoul/service/PopulationService.java
  src/main/java/com/example/whatseoul/service/PostService.java
  src/main/java/com/example/whatseoul/service/WebClientService.java
  src/main/java/com/example/whatseoul/util/LoginUtil.java
  src/main/java/com/example/whatseoul/util/TagName.java
  src/main/resources/115_.xlsx
  src/main/resources/static/css/citydata/citydatalist.css
  src/main/resources/templates/events.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postDetail.html
  src/main/resources/templates/post/postView.html
  src/main/resources/templates/postview.html
  src/main/resources/templates/user/register.html
  src/main/resources/templates/user/update.html
Labels: 🔥 MERGE
